// 시나리오 20종 — 신청서 §4-3 그대로 반영
import type { Scenario } from "@/lib/types";

export const SCENARIOS: Scenario[] = [
  { id: 1,  title: "서면역 EV 이용불가 + 유아동반 + 남포동 이동",
    query: { startStation: "서면역", endStation: "남포역", travelHour: 10, travelDow: 3, userType: "infant", preferences: ["safety", "low_congestion"] },
    expected: { mustBePassable: true, forbiddenTypes: ["이동 불가"] },
    checkPoint: "대체경로·혼잡회피" },
  { id: 2,  title: "부산역 도착 + 캐리어 + 고령 동반 + 광안리 이동",
    query: { startStation: "부산역", endStation: "광안역", travelHour: 12, travelDow: 5, userType: "luggage", preferences: ["safety"] },
    expected: { mustBePassable: true },
    checkPoint: "캐리어·고령자 조건" },
  { id: 3,  title: "연산역 환승 + 휠체어 + 해운대 이동",
    query: { startStation: "연산역", endStation: "해운대역", travelHour: 14, travelDow: 1, userType: "wheelchair", preferences: ["safety", "min_transfer"] },
    expected: { mustBePassable: true, forbiddenTypes: ["이동 불가"] },
    checkPoint: "환승역 복잡도" },
  { id: 4,  title: "사상역 혼잡 시간대 + 임산부 + 유니크베뉴 방문",
    query: { startStation: "사상역", endStation: "센텀시티역", travelHour: 18, travelDow: 4, userType: "pregnant", preferences: ["low_congestion", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "혼잡 회피" },
  { id: 5,  title: "남포역 EV 이용불가 + 관광약자 + 자갈치 방문",
    query: { startStation: "남포역", endStation: "자갈치역", travelHour: 11, travelDow: 6, userType: "elderly", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "대체 출입구 안내" },
  { id: 6,  title: "해운대역 주말 오후 + 가족관광 + 갈맷길 단구간",
    query: { startStation: "해운대역", endStation: "광안역", travelHour: 15, travelDow: 6, userType: "infant", preferences: ["include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "관광동선 확장" },
  { id: 7,  title: "광안리 야간행사 후 + 캐리어 + 부산역 복귀",
    query: { startStation: "광안역", endStation: "부산역", travelHour: 22, travelDow: 6, userType: "luggage", preferences: ["safety", "min_transfer"] },
    expected: { mustBePassable: true },
    checkPoint: "대형이벤트 후 혼잡" },
  { id: 8,  title: "센텀시티 MICE 방문 + 휠체어 동행",
    query: { startStation: "센텀시티역", endStation: "해운대역", travelHour: 10, travelDow: 2, userType: "wheelchair", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "유니크베뉴 연계" },
  { id: 9,  title: "동래역 환승 + 고령자 + 혼잡 회피 선호",
    query: { startStation: "동래역", endStation: "서면역", travelHour: 8, travelDow: 1, userType: "elderly", preferences: ["low_congestion", "min_transfer"] },
    expected: { mustBePassable: true },
    checkPoint: "환승 최소화" },
  { id: 10, title: "덕천역 이동 + 유아차 + 엘리베이터 회피 조건",
    query: { startStation: "덕천역", endStation: "서면역", travelHour: 13, travelDow: 2, userType: "infant", preferences: ["safety"] },
    expected: { mustBePassable: true },
    checkPoint: "층간 이동 부담" },
  { id: 11, title: "부산역 → 감천문화마을 + 고령 동반",
    query: { startStation: "부산역", endStation: "자갈치역", travelHour: 10, travelDow: 5, userType: "elderly", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "도시철도+관광지" },
  { id: 12, title: "서면 → 택슐랭 식당 + 저녁시간대",
    query: { startStation: "서면역", endStation: "서면역", travelHour: 19, travelDow: 5, userType: "general", preferences: ["include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "로컬상권 연결" },
  { id: 13, title: "수영역 환승 + 휠체어 + 해운대 목적",
    query: { startStation: "수영역", endStation: "해운대역", travelHour: 11, travelDow: 4, userType: "wheelchair", preferences: ["safety", "min_transfer"] },
    expected: { mustBePassable: true, forbiddenTypes: ["이동 불가"] },
    checkPoint: "환승 구조" },
  { id: 14, title: "자갈치역 → 갈맷길 저강도 코스",
    query: { startStation: "자갈치역", endStation: "남포역", travelHour: 14, travelDow: 6, userType: "elderly", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "도보 부담 조절" },
  { id: 15, title: "부산역 → 유니크베뉴 + MICE 참가자",
    query: { startStation: "부산역", endStation: "센텀시티역", travelHour: 9, travelDow: 2, userType: "general", preferences: ["include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "MICE 동선" },
  { id: 16, title: "행사 종료 후 아시아드 인근 → 숙소",
    query: { startStation: "서면역", endStation: "부산역", travelHour: 22, travelDow: 6, userType: "general", preferences: ["safety"] },
    expected: { mustBePassable: true },
    checkPoint: "대형이벤트 일반화" },
  { id: 17, title: "노포역 → 원도심 관광 + 고령자",
    query: { startStation: "노포역", endStation: "남포역", travelHour: 10, travelDow: 6, userType: "elderly", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "장거리 이동 부담" },
  { id: 18, title: "장산역 → 해운대 해변 + 유아동반",
    query: { startStation: "장산역", endStation: "해운대역", travelHour: 11, travelDow: 6, userType: "infant", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "관광약자 접근성" },
  { id: 19, title: "사하권 갈맷길 + 캐리어 관광객",
    query: { startStation: "자갈치역", endStation: "남포역", travelHour: 13, travelDow: 5, userType: "luggage", preferences: ["include_local", "safety"] },
    expected: { mustBePassable: true },
    checkPoint: "도보 난이도 제한" },
  { id: 20, title: "다국어 관광객 + 쉬운말 안내 필요",
    query: { startStation: "부산역", endStation: "해운대역", travelHour: 12, travelDow: 6, userType: "general", preferences: ["safety", "include_local"] },
    expected: { mustBePassable: true },
    checkPoint: "LLM 설명 품질" },
];
